CI: Start testing Python 3.12
pypa/wheel pull request #537
Opened 2023-06-06 17:05 UTC by EwoutH

Add Python 3.12 to the Ubuntu job matrix to start testing the betas in the CI.

2023-06-11 15:47 UTC, agronholm requested changes

2023-06-11 15:47 UTC, agronholm commented on .github/workflows/test.yml
> +      run: pip install setuptools
If setuptools is a crucial testing dependency, maybe it should instead be added to test dependencies in `pyproject.toml`?

2023-06-11 15:47 UTC, agronholm commented on .github/workflows/test.yml
> +        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12-dev", "pypy-3.8", "pypy-3.9"]
It would be preferable to use a combination of `"3.12"` and then `allow-prereleases: true` below.

2023-06-13 14:39 UTC, EwoutH commented
@agronholm Thanks for reviewing! I implemented your suggested changes.

2023-06-13 14:40 UTC, henryiii commented
I'll add a test to #529 once this goes in.

2023-06-13 21:52 UTC, merged

2023-06-13 21:52 UTC, agronholm commented
Thanks!